INFO  2015-11-09 16:04:18,047 [14] MeetingHub             - Meeting.Join (24, b7521d96-77c8-4684-91c4-086c695582a4)
ERROR 2015-11-09 16:04:48,665 [14] MeetingHub             - Meeting.Join  (24, b7521d96-77c8-4684-91c4-086c695582a4)
System.NullReferenceException: Object reference not set to an instance of an object.
   at RadialReview.Utilities.PermissionsUtility.Create(ISession session, UserOrganizationModel caller) in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Utilities\PermissionsUtility.cs:line 78
   at RadialReview.Accessors.PermissionsAccessor.Permitted(UserOrganizationModel caller, Action`1 ensurePermitted) in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Accessors\PermissionsAccessor.cs:line 29
   at RadialReview.Accessors.L10Accessor.JoinL10Meeting(UserOrganizationModel caller, Int64 recurrenceId, String connectionId) in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Accessors\L10Accessor.cs:line 1690
   at RadialReview.Hubs.MeetingHub.Join(Int64 meetingId, String connectionId) in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Hubs\MeetingHub.cs:line 75
INFO  2015-11-09 16:05:06,180 [5] MeetingHub             - Meeting.Join (24, 29227e25-0fae-4015-a3da-e4114bad71ae)
ERROR 2015-11-09 16:05:38,964 [5] MeetingHub             - Meeting.Join  (24, 29227e25-0fae-4015-a3da-e4114bad71ae)
System.NullReferenceException: Object reference not set to an instance of an object.
   at RadialReview.Utilities.PermissionsUtility.Create(ISession session, UserOrganizationModel caller) in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Utilities\PermissionsUtility.cs:line 78
   at RadialReview.Accessors.PermissionsAccessor.Permitted(UserOrganizationModel caller, Action`1 ensurePermitted) in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Accessors\PermissionsAccessor.cs:line 29
   at RadialReview.Accessors.L10Accessor.JoinL10Meeting(UserOrganizationModel caller, Int64 recurrenceId, String connectionId) in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Accessors\L10Accessor.cs:line 1690
   at RadialReview.Hubs.MeetingHub.Join(Int64 meetingId, String connectionId) in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Hubs\MeetingHub.cs:line 75
INFO  2015-11-09 16:05:51,615 [7] MeetingHub             - Meeting.Join (24, eed3fe7d-4884-4b4e-b4d7-4b04d52d31d6)
ERROR 2015-11-09 16:06:24,745 [7] MeetingHub             - Meeting.Join  (24, eed3fe7d-4884-4b4e-b4d7-4b04d52d31d6)
System.NullReferenceException: Object reference not set to an instance of an object.
   at RadialReview.Hubs.BaseHub.ForceGetUser(ISession s, String userId) in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Hubs\BaseHub.cs:line 25
   at RadialReview.Hubs.BaseHub.GetUser() in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Hubs\BaseHub.cs:line 70
   at RadialReview.Hubs.MeetingHub.Join(Int64 meetingId, String connectionId) in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Hubs\MeetingHub.cs:line 75
INFO  2015-11-09 16:07:07,003 [5] MeetingHub             - Meeting.Join (24, a39e7bc5-226c-4caa-a502-003e7bcb52a7)
INFO  2015-11-09 16:07:32,044 [8] MeetingHub             - Meeting.Join (24, 3710060a-6aed-44a9-bfc4-1c59d3291b39)
INFO  2015-11-09 16:09:44,762 [8] MeetingHub             - Meeting.Join (24, 7644f12a-c29f-417c-be9e-be61c4965bb3)
INFO  2015-11-09 16:10:06,262 [27] MeetingHub             - Meeting.Join (24, d86f3749-7d9d-4612-8c56-949b4ac4d9f6)
INFO  2015-11-09 16:10:06,935 [19] MeetingHub             - Meeting.Join (24, 36b02bfd-efaf-4d85-b36c-6bc6953b173b)
INFO  2015-11-09 16:20:02,128 [46] MeetingHub             - Meeting.Join (24, 71096b9f-f4c4-4190-816f-51558af388b3)
INFO  2015-11-09 16:20:02,128 [24] MeetingHub             - Meeting.Join (24, 2224148a-e883-4366-9cb0-fd2665d5aa05)
INFO  2015-11-09 16:20:02,366 [37] MeetingHub             - Meeting.Join (24, b4c724e3-20fa-4653-825f-c0d54ab97a2a)
ERROR 2015-11-11 13:52:43,370 [12] BaseController         - Error: [/Scheduler/EmailTodos?currentTime=1&taskId=2374]<<No row with the given identifier exists[NHibernate.Envers.DefaultRevisionEntity#25375]>>
NHibernate.ObjectNotFoundException: No row with the given identifier exists[NHibernate.Envers.DefaultRevisionEntity#25375]
   at NHibernate.Engine.ActionQueue.BeforeTransactionCompletionProcessQueue.BeforeTransactionCompletion()
   at NHibernate.Engine.ActionQueue.BeforeTransactionCompletion()
   at NHibernate.Impl.SessionImpl.BeforeTransactionCompletion(ITransaction tx)
   at NHibernate.Transaction.AdoTransaction.Commit()
   at RadialReview.Controllers.SchedulerController.<EmailTodos>d__2f.MoveNext() in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Controllers\SchedulerController.cs:line 220
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at lambda_method(Closure , Task )
   at System.Threading.Tasks.TaskHelpersExtensions.ThrowIfFaulted(Task task)
   at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass34.<BeginInvokeAsynchronousActionMethod>b__33(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass45.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3e()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass30.<BeginInvokeActionMethodWithFilters>b__2f(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass1e.<>c__DisplayClass28.<BeginInvokeAction>b__19()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass1e.<BeginInvokeAction>b__1b(IAsyncResult asyncResult)
ERROR 2015-11-11 13:52:52,020 [8] BaseAccessor           - Scheduled task error. 2374
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RadialReview.Accessors.TaskAccessor.<ExecuteTask>d__6.MoveNext() in c:\Users\Lynnea\Documents\GitHub\RadialReview\RadialReview\Accessors\TaskAccessor.cs:line 129
ERROR 2015-11-11 13:53:01,749 [5] AbstractBatcher        - Could not execute command: UPDATE `UserModel` SET UserName = ?p0, FirstName = ?p1, LastName = ?p2, SendTodoTime = ?p3, PasswordHash = ?p4, Hints = ?p5, CurrentRole = ?p6, _UserOrganizationIds = ?p7, SecurityStamp = ?p8, IsRadialAdmin = ?p9, DeleteTime = ?p10, ImageGuid = ?p11, Gender = ?p12, UserOrganizationCount = ?p13, ConsoleLog = ?p14 WHERE Id = ?p15
MySql.Data.MySqlClient.MySqlException (0x80004005): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.TimeoutException: Timeout in IO operation
   at MySql.Data.MySqlClient.TimedStream.StopTimer()
   at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlConnection.HandleTimeoutOrThreadAbort(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)
ERROR 2015-11-11 13:53:01,808 [7] AbstractBatcher        - Could not execute command: UPDATE `UserModel` SET UserName = ?p0, FirstName = ?p1, LastName = ?p2, SendTodoTime = ?p3, PasswordHash = ?p4, Hints = ?p5, CurrentRole = ?p6, _UserOrganizationIds = ?p7, SecurityStamp = ?p8, IsRadialAdmin = ?p9, DeleteTime = ?p10, ImageGuid = ?p11, Gender = ?p12, UserOrganizationCount = ?p13, ConsoleLog = ?p14 WHERE Id = ?p15
MySql.Data.MySqlClient.MySqlException (0x80004005): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.TimeoutException: Timeout in IO operation
   at MySql.Data.MySqlClient.TimedStream.StopTimer()
   at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlConnection.HandleTimeoutOrThreadAbort(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)
